<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Sf_config_model extends CI_Model
{

    public $table = 'sf_config';
    public $id = 'sf_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('sf_id', $q);
	$this->db->or_like('sf_table', $q);
	$this->db->or_like('sf_field', $q);
	$this->db->or_like('sf_type', $q);
	$this->db->or_like('sf_related', $q);
	$this->db->or_like('sf_label', $q);
	$this->db->or_like('sf_desc', $q);
	$this->db->or_like('sf_order', $q);
	$this->db->or_like('sf_hidden', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('sf_id', $q);
	$this->db->or_like('sf_table', $q);
	$this->db->or_like('sf_field', $q);
	$this->db->or_like('sf_type', $q);
	$this->db->or_like('sf_related', $q);
	$this->db->or_like('sf_label', $q);
	$this->db->or_like('sf_desc', $q);
	$this->db->or_like('sf_order', $q);
	$this->db->or_like('sf_hidden', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Sf_config_model.php */
/* Location: ./application/models/Sf_config_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-06-10 21:15:44 */
/* http://harviacode.com */