<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Telephones_model extends CI_Model
{

    public $table = 'telephones';
    public $id = 'idPhone';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

	// get data by idContact
	function get_by_idContact($id)
	{
		$this->db->select('numero');
		$this->db->where('idContact', $id);
		return $this->db->get($this->table)->result_array();
	}
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('idPhone', $q);
		$this->db->or_like('numero', $q);
		$this->db->or_like('idContact', $q);
		$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('idPhone', $q);
		$this->db->or_like('numero', $q);
		$this->db->or_like('idContact', $q);
		$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Telephones_model.php */
/* Location: ./application/models/Telephones_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-06-10 21:15:44 */
/* http://harviacode.com */
